### PR TITLE
Handle id attributes required

### PR DESCRIPTION
**Pull request by KentoMoriwaki**
`id` field in attributes cannot be null if exists

### CODE REVIEW

**Comment by KentoMoriwaki** [comment]
@ngtk please review

**Comment by ngtk** [comment]
we've talked to go with this. but, actually, it is our company's preference. 😅 
let me think again.

**Comment by KentoMoriwaki** [comment]
> we've talked to go with this. but, actually, it is our company's preference. 😅

Definitely. How about adding a option like `id_always_required` to handle this?

**Comment by ngtk** [comment]
> Definitely. How about add a option like `id_always_required` to handle this?

Looks good. or I can approve an option like `always_required_fields`(array of symbol).
I think either is fine. you can go with these ways.

**Comment by KentoMoriwaki** [comment]
@ngtk fixed.

**Comment by ngtk** [comment]
you need to fix the spec too.

**Comment by KentoMoriwaki** [comment]
@ngtk Fixed again.

**Review by ngtk — APPROVED** [review]
Looks great! 👍

**Pull request merged**
