### PR TITLE
Migrate to GitHub Actions, support Ruby 3.0 and support Rails 6.1

### PR DESCRIPTION
**Pull request by qnighy**
## Why

- We want to use the library with Ruby 3.0 / Rails 6.1.
- Travis now imposes a relatively tight limit on OSS projects and it sometimes fails due to credit shortage.

Related: https://github.com/ngtk/open_api/pull/12

## What

- Migrated from Travis CI to GitHub Actions.
  - It's not run in ngtk/open_api_annotator until it's merged, here's the result on my side: https://github.com/qnighy/open_api_annotator/actions/runs/1077754757
- Tested in  Ruby 3.0 too.
- Relaxed the version constraint on Rails.
  - Also configured the CI to test in various versions of Rails.

### CODE REVIEW

**Comment by qnighy** [comment]
@ngtk could you look at it?

**Review by ngtk — APPROVED** [review]
LGTM 👍  Thank you!

**Comment by ngtk** [comment]
GHA workflow passed ✅  https://github.com/ngtk/open_api_annotator/actions/runs/1115802868

**Comment by ngtk** [comment]
v0.6.0 which includes this change has been released.
https://rubygems.org/gems/open_api_annotator/versions/0.6.0

**Comment by qnighy** [comment]
Thanks a lot!

**Pull request merged**
